const FETCH_CATEGORIES_BEGIN = "FETCH_CATEGORIES_BEGIN";
const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
const FETCH_CATEGORIES_END = "FETCH_CATEGORIES_END";
const FETCH_PROPERTIES_BEGIN = "FETCH_PROPERTIES_BEGIN";
const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";
const FETCH_PROPERTIES_END = "FETCH_PROPERTIES_END";

module.exports = {
  FETCH_CATEGORIES_BEGIN,
  FETCH_CATEGORIES_SUCCESS,
  FETCH_CATEGORIES_END,
  FETCH_PROPERTIES_BEGIN,
  FETCH_PROPERTIES_SUCCESS,
  FETCH_PROPERTIES_END,
};
