const FETCH_USERS_BEGIN = "FETCH_USERS_BEGIN";
const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const FETCH_USER_ERROR = "FETCH_USER_ERROR";
const FETCH_DASHBOARD_BEGIN = "FETCH_DASHBOARD_BEGIN";
const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
const FETCH_DASHBOARD_ERROR = "FETCH_DASHBOARD_ERROR";
const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
const FETCH_TRANSACTONS_BEGIN = "FETCH_TRANSACTONS_BEGIN";
const FETCH_TRANSACTONS_SUCCESS = "FETCH_TRANSACTONS_SUCCESS";
const FETCH_TRANSACTONS_ERROR = "FETCH_TRANSACTONS_ERROR";
const ADD_USER_BEGIN = "ADD_USER_BEGIN";
const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
const ADD_USER_ERROR = "ADD_USER_ERROR";
const ADD_PRODUCT_BEGIN = "ADD_PRODUCT_BEGIN";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
const FETCH_BRANDS_BEGIN = "FETCH_BRANDS_BEGIN";
const FETCH_BRANDS_SUCCESS = "FETCH_BRANDS_SUCCESS";
const FETCH_BRANDS_ERROR = "FETCH_BRANDS_ERROR";
const FETCH_BRAND_BEGIN = "FETCH_BRAND_BEGIN";
const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";
const FETCH_BRAND_ERROR = "FETCH_BRAND_ERROR";
const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
const UPDATE_PRODUCT_BEGIN = "UPDATE_PRODUCT_BEGIN";
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";
const FETCH_PRODUCT_BEGIN = "FETCH_PRODUCT_BEGIN";
const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
const UPDATE_BRAND_BEGIN = "UPDATE_BRAND_BEGIN";
const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
const UPDATE_BRAND_ERROR = "UPDATE_BRAND_ERROR";
const DELETE_USER_BEGIN = "DELETE_USER_BEGIN";
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
const DELETE_USER_ERROR = "DELETE_USER_ERROR";
const DELETE_PRODUCT_BEGIN = "DELETE_PRODUCT_BEGIN";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
const DELETE_BRAND_BEGIN = "DELETE_BRAND_BEGIN";
const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
const DELETE_BRAND_ERROR = "DELETE_BRAND_ERROR";

module.exports = {
  FETCH_USERS_BEGIN,
  FETCH_USERS_SUCCESS,
  FETCH_USERS_ERROR,
  FETCH_DASHBOARD_BEGIN,
  FETCH_DASHBOARD_SUCCESS,
  FETCH_DASHBOARD_ERROR,
  FETCH_PRODUCTS_BEGIN,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_ERROR,
  FETCH_TRANSACTONS_BEGIN,
  FETCH_TRANSACTONS_SUCCESS,
  FETCH_TRANSACTONS_ERROR,
  ADD_USER_BEGIN,
  ADD_USER_SUCCESS,
  ADD_USER_ERROR,
  ADD_PRODUCT_BEGIN,
  ADD_PRODUCT_SUCCESS,
  ADD_PRODUCT_ERROR,
  FETCH_BRANDS_BEGIN,
  FETCH_BRANDS_SUCCESS,
  FETCH_BRANDS_ERROR,
  FETCH_BRAND_BEGIN,
  FETCH_BRAND_SUCCESS,
  FETCH_BRAND_ERROR,
  FETCH_USER_BEGIN,
  FETCH_USER_SUCCESS,
  FETCH_USER_ERROR,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
  UPDATE_PRODUCT_BEGIN,
  UPDATE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_ERROR,
  FETCH_PRODUCT_BEGIN,
  FETCH_PRODUCT_SUCCESS,
  FETCH_PRODUCT_ERROR,
  UPDATE_BRAND_BEGIN,
  UPDATE_BRAND_SUCCESS,
  UPDATE_BRAND_ERROR,
  DELETE_USER_BEGIN,
  DELETE_USER_SUCCESS,
  DELETE_USER_ERROR,
  DELETE_PRODUCT_BEGIN,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_ERROR,
  DELETE_BRAND_BEGIN,
  DELETE_BRAND_SUCCESS,
  DELETE_BRAND_ERROR,
};
