const FETCH_CART_BEGIN = "FETCH_CART_BEGIN";
const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
const FETCH_CART_ERROR = "FETCH_CART_ERROR";
const ADD_CARTITEM_BEGIN = "ADD_CARTITEM_BEGIN";
const ADD_CARTITEM_SUCCESS = "ADD_CARTITEM_SUCCESS";
const ADD_CARTITEM_ERROR = "ADD_CARTITEM_ERROR";

module.exports = {
  FETCH_CART_BEGIN,
  FETCH_CART_SUCCESS,
  FETCH_CART_ERROR,
  ADD_CARTITEM_BEGIN,
  ADD_CARTITEM_SUCCESS,
  ADD_CARTITEM_ERROR,
};
