const FETCH_PRODUCT_BEGIN = "FETCH_PRODUCT_BEGIN";
const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
const FETCH_PHONE_SUCCESS = "FETCH_PHONE_SUCCESS";
const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

module.exports = {
  FETCH_PRODUCT_BEGIN,
  FETCH_PRODUCT_SUCCESS,
  FETCH_PHONE_SUCCESS,
  FETCH_PRODUCT_ERROR,
};
