const FETCH_PRODUCT_BEGIN = "FETCH_PRODUCT_BEGIN";
const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
const FETCH_PHONE_SUCCESS = "FETCH_PHONE_SUCCESS";
const FETCH_LAPTOP_SUCCESS = "FETCH_LAPTOP_SUCCESS";
const FETCH_HEADPHONE_SUCCESS = "FETCH_HEADPHONE_SUCCESS";
const FETCH_ACCESSORIES_SUCCESS = "FETCH_ACCESSORIES_SUCCESS";
const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
const CHANGE_DISPLAY_PRODUCT = "CHANGE_DISPLAY_PRODUCT";

module.exports = {
  FETCH_PRODUCT_BEGIN,
  FETCH_PRODUCT_SUCCESS,
  FETCH_PHONE_SUCCESS,
  FETCH_LAPTOP_SUCCESS,
  FETCH_HEADPHONE_SUCCESS,
  FETCH_ACCESSORIES_SUCCESS,
  FETCH_PRODUCT_ERROR,
  CHANGE_DISPLAY_PRODUCT,
};
