// products
const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

// product
const FETCH_SINGLE_PRODUCT_BEGIN = "FETCH_SINGLE_PRODUCT_BEGIN";
const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
const FETCH_SINGLE_PRODUCT_ERROR = "FETCH_SINGLE_PRODUCT_ERROR";

// brand
const FETCH_BRANDS_BEGIN = "FETCH_BRANDS_BEGIN";
const FETCH_BRANDS_SUCCESS = "FETCH_BRANDS_SUCCESS";
const FETCH_BRANDS_ERROR = "FETCH_BRANDS_ERROR";

// categories ?
const FETCH_CATEGORIES_BEGIN = "FETCH_CATEGORIES_BEGIN";
const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
const FETCH_PROPERTIES_BEGIN = "FETCH_PROPERTIES_BEGIN";
const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";

module.exports = {
  FETCH_PRODUCTS_BEGIN,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_ERROR,
  FETCH_CATEGORIES_BEGIN,
  FETCH_CATEGORIES_SUCCESS,
  FETCH_PROPERTIES_BEGIN,
  FETCH_PROPERTIES_SUCCESS,
  FETCH_SINGLE_PRODUCT_BEGIN,
  FETCH_SINGLE_PRODUCT_SUCCESS,
  FETCH_SINGLE_PRODUCT_ERROR,
  FETCH_BRANDS_BEGIN,
  FETCH_BRANDS_SUCCESS,
  FETCH_BRANDS_ERROR,
};
