const TRANSACTION_BEGIN = "TRANSACTION_BEGIN";
const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
const TRANSACTION_ERROR = "TRANSACTION_ERROR";
const FETCH_TRANSACTION_BEGIN = "FETCH_TRANSACTION_BEGIN";
const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";
const FETCH_TRANSACTION_ERROR = "FETCH_TRANSACTION_ERROR";
const FETCH_SINGLE_TRANSACTION_BEGIN = "FETCH_SINGLE_TRANSACTION_BEGIN";
const FETCH_SINGLE_TRANSACTION_SUCCESS = "FETCH_SINGLE_TRANSACTION_SUCCESS";
const FETCH_SINGLE_TRANSACTION_ERROR = "FETCH_SINGLE_TRANSACTION_ERROR";
const GETME_DONE = "GETME_DONE";

module.exports = {
  TRANSACTION_BEGIN,
  TRANSACTION_SUCCESS,
  TRANSACTION_ERROR,
  FETCH_TRANSACTION_BEGIN,
  FETCH_TRANSACTION_SUCCESS,
  FETCH_TRANSACTION_ERROR,
  FETCH_SINGLE_TRANSACTION_BEGIN,
  FETCH_SINGLE_TRANSACTION_SUCCESS,
  FETCH_SINGLE_TRANSACTION_ERROR,
  GETME_DONE,
};
