const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

module.exports = { LOGIN_USER_BEGIN, LOGIN_USER_SUCCESS, LOGIN_USER_ERROR };
