const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
const LOGOUT_USER_BEGIN = "LOGOUT_USER_BEGIN";
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";
const SIGNUP_USER_BEGIN = "SIGNUP_USER_BEGIN";
const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR";
const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

module.exports = {
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  LOGOUT_USER_BEGIN,
  LOGOUT_USER_SUCCESS,
  LOGOUT_USER_ERROR,
  SIGNUP_USER_BEGIN,
  SIGNUP_USER_SUCCESS,
  SIGNUP_USER_ERROR,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
};
